title = "Molecule"
baseURL = "http://scalamolecule.org/"
languageCode = "en-us"
metaDataFormat = "yaml"
pygmentsStyle = "perldoc"

[[menu.main]]
    name = "Compare"
    weight = 10
    identifier = "compare"
    url = "/compare/"
[[menu.main]]
    name = "Resources"
    weight = 20
    identifier = "resources"
    url = "/resources/"
[[menu.main]]
    name = "Docs"
    weight = 30
    identifier = "docs"
    url = "/docs/"
[[menu.main]]
    name = "Dev"
    weight = 40
    identifier = "dev"
    url = "/dev/"
[[menu.main]]
    name = "Community"
    weight = 50
    identifier = "community"
    url = "/community/"