title = "Molecule"
baseURL = "http://scalamolecule.org/"
languageCode = "en-us"
metaDataFormat = "yaml"
pygmentsStyle = "perldoc"
uglifyUrls = false
disablePathToLower = true

[[menu.main]]
    name = "Compare"
    weight = 10
    identifier = "compare"
    url = "/compare/"

[[menu.main]]
    name = "Resources"
    weight = 20
    identifier = "resources"
    url = "/resources/"

[[menu.main]]
    name = "Manual"
    weight = 30
    identifier = "manual"
    url = "/manual/"


# API ============================================================

[[menu.main]]
    name = "API docs"
    weight = 40
    identifier = "api"
    url = "/api/molecule"

[[menu.main]]
    name = "action"
    weight = 1
    parent = "api"
    identifier = "api-action"
    url = "/api/molecule/action"
[[menu.main]]
    name = "CompositeInserts"
    parent = "api-action"
    identifier = "api-action-CompositeInserts"
    url = "/api/molecule/action/CompositeInserts.html"
[[menu.main]]
    name = "Entity"
    parent = "api-action"
    identifier = "api-action-Entity"
    url = "/api/molecule/action/Entity.html"
[[menu.main]]
    name = "EntityOps"
    parent = "api-action"
    identifier = "api-action-EntityOps"
    url = "/api/molecule/action/EntityOps.html"
[[menu.main]]
    name = "Molecule"
    parent = "api-action"
    identifier = "api-action-Molecule"
    url = "/api/molecule/action/Molecule.html"
[[menu.main]]
    name = "OptionalMapOps"
    parent = "api-action"
    identifier = "api-action-OptionalMapOps"
    url = "/api/molecule/action/OptionalMapOps.html"

[[menu.main]]
    name = "composition"
    parent = "api"
    identifier = "api-composition"
    url = "/api/molecule/composition"
[[menu.main]]
    name = "Composite"
    parent = "api-composition"
    identifier = "api-composition-Composite"
    url = "/api/molecule/composition/Composite.html"
[[menu.main]]
    name = "CompositeInit"
    parent = "api-composition"
    identifier = "api-composition-CompositeInit"
    url = "/api/molecule/composition/CompositeInit.html"
[[menu.main]]
    name = "CompositeInit_In_1"
    parent = "api-composition"
    identifier = "api-composition-CompositeInit_In_1"
    url = "/api/molecule/composition/CompositeInit_In_1.html"
[[menu.main]]
    name = "CompositeInit_In_2"
    parent = "api-composition"
    identifier = "api-composition-CompositeInit_In_2"
    url = "/api/molecule/composition/CompositeInit_In_2.html"
[[menu.main]]
    name = "CompositeInit_In_3"
    parent = "api-composition"
    identifier = "api-composition-CompositeInit_In_3"
    url = "/api/molecule/composition/CompositeInit_In_3.html"
[[menu.main]]
    name = "Composite_In_1"
    parent = "api-composition"
    identifier = "api-composition-Composite_In_1"
    url = "/api/molecule/composition/Composite_In_1.html"
[[menu.main]]
    name = "Composite_In_2"
    parent = "api-composition"
    identifier = "api-composition-Composite_In_2"
    url = "/api/molecule/composition/Composite_In_2.html"
[[menu.main]]
    name = "Composite_In_3"
    parent = "api-composition"
    identifier = "api-composition-Composite_In_3"
    url = "/api/molecule/composition/Composite_In_3.html"
[[menu.main]]
    name = "Nested"
    parent = "api-composition"
    identifier = "api-composition-Nested"
    url = "/api/molecule/composition/Nested.html"
[[menu.main]]
    name = "Nested_In_1"
    parent = "api-composition"
    identifier = "api-composition-Nested_In_1"
    url = "/api/molecule/composition/Nested_In_1.html"
[[menu.main]]
    name = "Nested_In_2"
    parent = "api-composition"
    identifier = "api-composition-Nested_In_2"
    url = "/api/molecule/composition/Nested_In_2.html"
[[menu.main]]
    name = "Nested_In_3"
    parent = "api-composition"
    identifier = "api-composition-Nested_In_3"
    url = "/api/molecule/composition/Nested_In_3.html"
[[menu.main]]
    name = "Tx"
    parent = "api-composition"
    identifier = "api-composition-Tx"
    url = "/api/molecule/composition/Tx.html"

[[menu.main]]
    name = "exceptions"
    parent = "api"
    identifier = "api-exceptions"
    url = "/api/molecule/exceptions"
[[menu.main]]
    name = "MoleculeException"
    parent = "api-exceptions"
    identifier = "api-exceptions-MoleculeException"
    url = "/api/molecule/exceptions/package%24?%24?MoleculeException.html"
[[menu.main]]
    name = "QueryException"
    parent = "api-exceptions"
    identifier = "api-exceptions-QueryException"
    url = "/api/molecule/exceptions/package%24?%24?QueryException.html"

[[menu.main]]
    name = "expression"
    parent = "api"
    identifier = "api-expression"
    url = "/api/molecule/expression"
[[menu.main]]
    name = "AggregateKeywords"
    parent = "api-expression"
    identifier = "api-expression-AggregateKeywords"
    url = "/api/molecule/expression/AggregateKeywords.html"
[[menu.main]]
    name = "AttrExpressions"
    parent = "api-expression"
    identifier = "api-expression-AttrExpressions"
    url = "/api/molecule/expression/AttrExpressions.html"

[[menu.main]]
    name = "facade"
    parent = "api"
    identifier = "api-facade"
    url = "/api/molecule/facade"
[[menu.main]]
    name = "Conn"
    parent = "api-facade"
    identifier = "api-facade-Conn"
    url = "/api/molecule/facade/Conn.html"
[[menu.main]]
    name = "Datomic"
    parent = "api-facade"
    identifier = "api-facade-Datomic"
    url = "/api/molecule/facade/Datomic.html"
[[menu.main]]
    name = "TxReport"
    parent = "api-facade"
    identifier = "api-facade-TxReport"
    url = "/api/molecule/facade/TxReport.html"

[[menu.main]]
    name = "factory"
    parent = "api"
    identifier = "api-factory"
    url = "/api/molecule/factory"
[[menu.main]]
    name = "Composite_Factory"
    parent = "api-factory"
    identifier = "api-factory-Composite_Factory"
    url = "/api/molecule/factory/Composite_Factory.html"
[[menu.main]]
    name = "Composite_In_1_Factory"
    parent = "api-factory"
    identifier = "api-factory-Composite_In_1_Factory"
    url = "/api/molecule/factory/Composite_In_1_Factory.html"
[[menu.main]]
    name = "Composite_In_2_Factory"
    parent = "api-factory"
    identifier = "api-factory-Composite_In_2_Factory"
    url = "/api/molecule/factory/Composite_In_2_Factory.html"
[[menu.main]]
    name = "Composite_In_3_Factory"
    parent = "api-factory"
    identifier = "api-factory-Composite_In_3_Factory"
    url = "/api/molecule/factory/Composite_In_3_Factory.html"
[[menu.main]]
    name = "Molecule_Factory"
    parent = "api-factory"
    identifier = "api-factory-Molecule_Factory"
    url = "/api/molecule/factory/Molecule_Factory.html"
[[menu.main]]
    name = "Molecule_In_1_Factory"
    parent = "api-factory"
    identifier = "api-factory-Molecule_In_1_Factory"
    url = "/api/molecule/factory/Molecule_In_1_Factory.html"
[[menu.main]]
    name = "Molecule_In_2_Factory"
    parent = "api-factory"
    identifier = "api-factory-Molecule_In_2_Factory"
    url = "/api/molecule/factory/Molecule_In_2_Factory.html"
[[menu.main]]
    name = "Molecule_In_3_Factory"
    parent = "api-factory"
    identifier = "api-factory-Molecule_In_3_Factory"
    url = "/api/molecule/factory/Molecule_In_3_Factory.html"

[[menu.main]]
    name = "generic"
    parent = "api"
    identifier = "api-generic"
    url = "/api/molecule/generic"
[[menu.main]]
    name = "Datom"
    parent = "api-generic"
    identifier = "api-generic-Datom"
    url = "/api/molecule/generic/Datom.html"
[[menu.main]]
    name = "Db"
    parent = "api-generic"
    identifier = "api-generic-Db"
    url = "/api/molecule/generic/Db.html"

[[menu.main]]
    name = "input"
    parent = "api"
    identifier = "api-input"
    url = "/api/molecule/input"
[[menu.main]]
    name = "InputMolecule"
    parent = "api-input"
    identifier = "api-input-InputMolecule"
    url = "/api/molecule/input/InputMolecule.html"
[[menu.main]]
    name = "InputMolecule_1"
    parent = "api-input"
    identifier = "api-input-InputMolecule_1"
    url = "/api/molecule/input/InputMolecule_1.html"
[[menu.main]]
    name = "InputMolecule_2"
    parent = "api-input"
    identifier = "api-input-InputMolecule_2"
    url = "/api/molecule/input/InputMolecule_2.html"
[[menu.main]]
    name = "InputMolecule_3"
    parent = "api-input"
    identifier = "api-input-InputMolecule_3"
    url = "/api/molecule/input/InputMolecule_3.html"

[[menu.main]]
    name = "schema"
    parent = "api"
    identifier = "api-schema"
    url = "/api/molecule/schema"
[[menu.main]]
    name = "SchemaTransaction"
    parent = "api-schema"
    identifier = "api-schema-SchemaTransaction"
    url = "/api/molecule/schema/SchemaTransaction.html"
[[menu.main]]
    name = "definition"
    parent = "api-schema"
    identifier = "api-schema-definition"
    url = "/api/molecule/schema/definition%24?.html"

# end of API ============================================================


[[menu.main]]
    name = "Dev"
    weight = 50
    identifier = "dev"
    url = "/dev/"


[[menu.main]]
    name = "Community"
    weight = 60
    identifier = "community"
    url = "/community/"
[[menu.main]]
    name = "Forum"
    weight = 61
    parent = "community"
    identifier = "forum"
    url = "https://groups.google.com/forum/#!forum/molecule-dsl"
[[menu.main]]
    name = "Github"
    weight = 62
    parent = "community"
    identifier = "github"
    url = "https://github.com/scalamolecule/molecule"
[[menu.main]]
    name = "Molecule issues"
    weight = 62
    parent = "community"
    identifier = "molecule-issues"
    url = "https://github.com/scalamolecule/molecule/issues"
[[menu.main]]
    name = "Molecule docs issues"
    weight = 63
    parent = "community"
    identifier = "molecule-docs-issues"
    url = "https://github.com/scalamolecule/molecule-docs/issues"