title = "Molecule"
baseURL = "http://scalamolecule.org/"
languageCode = "en-us"
metaDataFormat = "yaml"
pygmentsStyle = "perldoc"
uglifyUrls = false
disablePathToLower = true
relativeURLs = true
canonifyURLs = true

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 2

[[menu.main]]
    weight = 10
    name = "Intro"
    identifier = "intro"
    url = "/intro/"


[[menu.main]]
    weight = 20
    name = "Setup"
    identifier = "setup"
    url = "/setup/"


[[menu.main]]
    weight = 30
    name = "Code"
    identifier = "code"
    url = "/code/"
    [menu.main.params]
        anchors = true

[[menu.main]]
    weight = 200
    parent = "code"
    name = "ScalaDocs"
    identifier = "docs"
    url = "https://javadoc.io/doc/org.scalamolecule/molecule_2.13/latest/index.html"


[[menu.main]]
    weight = 40
    name = "Deploy"
    identifier = "deploy"
    url = "/deploy/"


[[menu.main]]
    name = "Admin"
    weight = 50
    identifier = "admin"
    url = "/admin/"

[[menu.main]]
    weight = 60
    name = "Dev"
    identifier = "dev"
    url = "/dev/"


[[menu.main]]
    name = "Blog"
    weight = 70
    identifier = "blog"
    url = "/blog/"

[[menu.main]]
    name = "Community"
    weight = 80
    identifier = "community"
    url = "/community/"




