title = "Molecule"
baseURL = "http://scalamolecule.org/"
languageCode = "en-us"
metaDataFormat = "yaml"
pygmentsStyle = "perldoc"
uglifyUrls = false
disablePathToLower = true

[[menu.main]]
    weight = 10
    name = "Compare"
    identifier = "compare"
    url = "/compare/"

[[menu.main]]
    weight = 20
    name = "Resources"
    identifier = "resources"
    url = "/resources/"

[[menu.main]]
    weight = 30
    name = "Manual"
    identifier = "manual"
    url = "/manual/"


# Docs ============================================================

[[menu.main]]
    weight = 40
    name = "Docs"
    identifier = "docs"
    url = "/api/molecule"


[[menu.main]]
    parent = "docs"
    name = "api"
    identifier = "docs-api"
    url = "/api/molecule/api"
[[menu.main]]
    parent = "docs-api"
    name = "exception"
    identifier = "docs-api-exception"
    url = "/api/molecule/api/exception"
[[menu.main]]
    parent = "docs-api"
    name = "get"
    identifier = "docs-api-get"
    url = "/api/molecule/api/get"
[[menu.main]]
    parent = "docs-api"
    name = "getAsync"
    identifier = "docs-api-getAsync"
    url = "/api/molecule/api/getAsync"
[[menu.main]]
    parent = "docs-api"
    name = "Entity"
    identifier = "docs-api-Entity"
    url = "/api/molecule/api/Entity.html"
[[menu.main]]
    parent = "docs-api"
    name = "EntityOps"
    identifier = "docs-api-EntityOps"
    url = "/api/molecule/api/EntityOps.html"
[[menu.main]]
    parent = "docs-api"
    name = "Molecule"
    identifier = "docs-api-Molecule"
    url = "/api/molecule/api/Molecule.html"
[[menu.main]]
    parent = "docs-api"
    name = "OptionalMapOps"
    identifier = "docs-api-OptionalMapOps"
    url = "/api/molecule/api/OptionalMapOps.html"
[[menu.main]]
    parent = "docs-api"
    name = "ShowDebug"
    identifier = "docs-api-ShowDebug"
    url = "/api/molecule/api/ShowDebug.html"
[[menu.main]]
    parent = "docs-api"
    name = "TxMethods"
    identifier = "docs-api-TxMethods"
    url = "/api/molecule/api/TxMethods.html"


[[menu.main]]
    parent = "docs"
    name = "composition"
    identifier = "docs-composition"
    url = "/api/molecule/composition"
[[menu.main]]
    parent = "docs-composition"
    name = "Composite"
    identifier = "docs-composition-Composite"
    url = "/api/molecule/composition/Composite.html"
[[menu.main]]
    parent = "docs-composition"
    name = "CompositeInit"
    identifier = "docs-composition-CompositeInit"
    url = "/api/molecule/composition/CompositeInit.html"
[[menu.main]]
    parent = "docs-composition"
    name = "CompositeInit_In_1"
    identifier = "docs-composition-CompositeInit_In_1"
    url = "/api/molecule/composition/CompositeInit_In_1.html"
[[menu.main]]
    parent = "docs-composition"
    name = "CompositeInit_In_2"
    identifier = "docs-composition-CompositeInit_In_2"
    url = "/api/molecule/composition/CompositeInit_In_2.html"
[[menu.main]]
    parent = "docs-composition"
    name = "CompositeInit_In_3"
    identifier = "docs-composition-CompositeInit_In_3"
    url = "/api/molecule/composition/CompositeInit_In_3.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Composite_In_1"
    identifier = "docs-composition-Composite_In_1"
    url = "/api/molecule/composition/Composite_In_1.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Composite_In_2"
    identifier = "docs-composition-Composite_In_2"
    url = "/api/molecule/composition/Composite_In_2.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Composite_In_3"
    identifier = "docs-composition-Composite_In_3"
    url = "/api/molecule/composition/Composite_In_3.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Nested"
    identifier = "docs-composition-Nested"
    url = "/api/molecule/composition/Nested.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Nested_In_1"
    identifier = "docs-composition-Nested_In_1"
    url = "/api/molecule/composition/Nested_In_1.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Nested_In_2"
    identifier = "docs-composition-Nested_In_2"
    url = "/api/molecule/composition/Nested_In_2.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Nested_In_3"
    identifier = "docs-composition-Nested_In_3"
    url = "/api/molecule/composition/Nested_In_3.html"
[[menu.main]]
    parent = "docs-composition"
    name = "Tx"
    identifier = "docs-composition-Tx"
    url = "/api/molecule/composition/Tx.html"


[[menu.main]]
    parent = "docs"
    name = "exceptions"
    identifier = "docs-exceptions"
    url = "/api/molecule/exceptions"
[[menu.main]]
    parent = "docs-exceptions"
    name = "MoleculeCompileException"
    identifier = "docs-exceptions-MoleculeCompileException"
    url = "/api/molecule/exceptions/package%24?%24?MoleculeCompileException.html"
[[menu.main]]
    parent = "docs-exceptions"
    name = "MoleculeException"
    identifier = "docs-exceptions-MoleculeException"
    url = "/api/molecule/exceptions/package%24?%24?MoleculeException.html"
[[menu.main]]
    parent = "docs-exceptions"
    name = "QueryException"
    identifier = "docs-exceptions-QueryException"
    url = "/api/molecule/exceptions/package%24?%24?QueryException.html"


[[menu.main]]
    parent = "docs"
    name = "expression"
    identifier = "docs-expression"
    url = "/api/molecule/expression"
[[menu.main]]
    parent = "docs-expression"
    name = "AggregateKeywords"
    identifier = "docs-expression-AggregateKeywords"
    url = "/api/molecule/expression/AggregateKeywords.html"
[[menu.main]]
    parent = "docs-expression"
    name = "AttrExpressions"
    identifier = "docs-expression-AttrExpressions"
    url = "/api/molecule/expression/AttrExpressions.html"
[[menu.main]]
    parent = "docs-expression"
    name = "AttrExpressions"
    identifier = "docs-expression-AttrExpressions"
    url = "/api/molecule/expression/LogicImplicits.html"


[[menu.main]]
    parent = "docs"
    name = "facade"
    identifier = "docs-facade"
    url = "/api/molecule/facade"
[[menu.main]]
    parent = "docs-facade"
    name = "exception"
    identifier = "docs-facade-exception"
    url = "/api/molecule/facade/exception"
[[menu.main]]
    parent = "docs-facade"
    name = "Conn"
    identifier = "docs-facade-Conn"
    url = "/api/molecule/facade/Conn.html"
[[menu.main]]
    parent = "docs-facade"
    name = "Datomic"
    identifier = "docs-facade-Datomic"
    url = "/api/molecule/facade/Datomic.html"
[[menu.main]]
    parent = "docs-facade"
    name = "TxReport"
    identifier = "docs-facade-TxReport"
    url = "/api/molecule/facade/TxReport.html"


[[menu.main]]
    parent = "docs"
    name = "factory"
    identifier = "docs-factory"
    url = "/api/molecule/factory"
[[menu.main]]
    parent = "docs-factory"
    name = "Composite_Factory2"
    identifier = "docs-factory-Composite_Factory2"
    url = "/api/molecule/factory/Composite_Factory2.html"
[[menu.main]]
    parent = "docs-factory"
    name = "Composite_In_1_Factory2"
    identifier = "docs-factory-Composite_In_1_Factory2"
    url = "/api/molecule/factory/Composite_In_1_Factory2.html"
[[menu.main]]
    parent = "docs-factory"
    name = "Composite_In_2_Factory2"
    identifier = "docs-factory-Composite_In_2_Factory2"
    url = "/api/molecule/factory/Composite_In_2_Factory2.html"
[[menu.main]]
    parent = "docs-factory"
    name = "Composite_In_3_Factory2"
    identifier = "docs-factory-Composite_In_3_Factory2"
    url = "/api/molecule/factory/Composite_In_3_Factory2.html"
[[menu.main]]
    parent = "docs-factory"
    name = "Molecule_Factory2"
    identifier = "docs-factory-Molecule_Factory2"
    url = "/api/molecule/factory/Molecule_Factory2.html"
[[menu.main]]
    parent = "docs-factory"
    name = "Molecule_In_1_Factory2"
    identifier = "docs-factory-Molecule_In_1_Factory2"
    url = "/api/molecule/factory/Molecule_In_1_Factory2.html"
[[menu.main]]
    parent = "docs-factory"
    name = "Molecule_In_2_Factory2"
    identifier = "docs-factory-Molecule_In_2_Factory2"
    url = "/api/molecule/factory/Molecule_In_2_Factory2.html"
[[menu.main]]
    parent = "docs-factory"
    name = "Molecule_In_3_Factory2"
    identifier = "docs-factory-Molecule_In_3_Factory2"
    url = "/api/molecule/factory/Molecule_In_3_Factory2.html"


[[menu.main]]
    parent = "docs"
    name = "generic"
    identifier = "docs-generic"
    url = "/api/molecule/generic"
[[menu.main]]
    parent = "docs-generic"
    name = "Datom"
    identifier = "docs-generic-Datom"
    url = "/api/molecule/generic/datom/index.html"
[[menu.main]]
    parent = "docs-generic"
    name = "Index"
    identifier = "docs-generic-Index"
    url = "/api/molecule/generic/index/index.html"
[[menu.main]]
    parent = "docs-generic"
    name = "Schema"
    identifier = "docs-generic-Schema"
    url = "/api/molecule/generic/schema/index.html"
[[menu.main]]
    parent = "docs-generic"
    name = "Log"
    identifier = "docs-generic-Log"
    url = "/api/molecule/generic/Log.html"


[[menu.main]]
    parent = "docs"
    name = "input"
    identifier = "docs-input"
    url = "/api/molecule/input"
[[menu.main]]
    parent = "docs-input"
    name = "exception"
    identifier = "docs-input-exception"
    url = "/api/molecule/input/exception"
[[menu.main]]
    parent = "docs-input"
    name = "InputMolecule"
    identifier = "docs-input-InputMolecule"
    url = "/api/molecule/input/InputMolecule.html"
[[menu.main]]
    parent = "docs-input"
    name = "InputMolecule_1"
    identifier = "docs-input-InputMolecule_1"
    url = "/api/molecule/input/InputMolecule_1.html"
[[menu.main]]
    parent = "docs-input"
    name = "InputMolecule_2"
    identifier = "docs-input-InputMolecule_2"
    url = "/api/molecule/input/InputMolecule_2.html"
[[menu.main]]
    parent = "docs-input"
    name = "InputMolecule_3"
    identifier = "docs-input-InputMolecule_3"
    url = "/api/molecule/input/InputMolecule_3.html"


[[menu.main]]
    parent = "docs"
    name = "macros"
    identifier = "docs-macros"
    url = "/api/molecule/macros"
[[menu.main]]
    parent = "docs-macros"
    name = "TxFns"
    identifier = "docs-macros-TxFns"
    url = "/api/molecule/macros/TxFns.html"


[[menu.main]]
    parent = "docs"
    name = "schema"
    identifier = "docs-schema"
    url = "/api/molecule/schema"
[[menu.main]]
    parent = "docs-schema"
    name = "SchemaTransaction"
    identifier = "docs-schema-SchemaTransaction"
    url = "/api/molecule/schema/SchemaTransaction.html"
[[menu.main]]
    parent = "docs-schema"
    name = "definition"
    identifier = "docs-schema-definition"
    url = "/api/molecule/schema/definition%24?.html"

# end of Docs ============================================================


[[menu.main]]
    weight = 50
    name = "Dev"
    identifier = "dev"
    url = "/dev/"


[[menu.main]]
    name = "Community"
    weight = 60
    identifier = "community"
    url = "/community/"
[[menu.main]]
    weight = 61
    parent = "community"
    name = "Gitter"
    identifier = "gitter"
    url = "https://gitter.im/scalamolecule/Lobby"
[[menu.main]]
    weight = 62
    parent = "community"
    name = "Forum"
    identifier = "forum"
    url = "https://groups.google.com/forum/#!forum/molecule-dsl"
[[menu.main]]
    weight = 63
    parent = "community"
    name = "Github"
    identifier = "github"
    url = "https://github.com/scalamolecule/molecule"
[[menu.main]]
    weight = 64
    parent = "community"
    name = "Molecule issues"
    identifier = "molecule-issues"
    url = "https://github.com/scalamolecule/molecule/issues"
[[menu.main]]
    weight = 65
    parent = "community"
    name = "Molecule docs issues"
    identifier = "molecule-docs-issues"
    url = "https://github.com/scalamolecule/molecule-web/issues"